'use client'
import {useEffect,useMemo,useState} from 'react'
function dt(v:string){if(!v)return '';try{return new Intl.DateTimeFormat('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
export default function Notes(){
 const[items,setItems]=useState<any[]>([]),[title,setTitle]=useState(''),[content,setContent]=useState(''),[remindAt,setRemindAt]=useState(''),[q,setQ]=useState(''),[msg,setMsg]=useState('')
 async function load(){const r=await fetch('/api/notes');const d=await r.json();setItems(d.items||[]);if(!r.ok)setMsg(d.hint||d.error||'Không tải được ghi chú')}
 useEffect(()=>{load()},[])
 async function add(){if(!title.trim()&&!content.trim())return setMsg('Nhập tiêu đề hoặc nội dung.');const r=await fetch('/api/notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,content,remindAt:remindAt?new Date(remindAt).toISOString():null})});const d=await r.json();if(!r.ok)return setMsg(d.hint||d.error||'Không lưu được');setTitle('');setContent('');setRemindAt('');setMsg('Đã lưu ✓');load()}
 async function patch(id:string,p:any){await fetch('/api/notes/item',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...p})});load()}
 async function del(id:string){if(!confirm('Xóa ghi chú này?'))return;await fetch('/api/notes/item',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});load()}
 const filtered=useMemo(()=>{const s=q.toLowerCase();return items.filter(x=>!s||`${x.title} ${x.content}`.toLowerCase().includes(s))},[items,q])
 return <><header className="libraryHeader"><div><span className="eyebrow">QUICK NOTES</span><h1>Ghi chú</h1><p>Ghi nhanh điều cần nhớ, việc nhỏ hoặc lịch hẹn. Ngày giờ tạo được lưu tự động.</p></div></header>
 <section className="quickNoteComposer"><div className="noteComposerGrid"><label>Tiêu đề<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Gọi cho khách hàng"/></label><label>Lịch hẹn <span className="optional">(tùy chọn)</span><input type="datetime-local" value={remindAt} onChange={e=>setRemindAt(e.target.value)}/></label></div><label>Nội dung<textarea rows={3} value={content} onChange={e=>setContent(e.target.value)} placeholder="Điều cần nhớ…"/></label><div className="captureBottom"><span>{msg}</span><button className="primary" onClick={add}>＋ Lưu ghi chú</button></div></section>
 <section className="notesBoard"><div className="denseTop"><div><span className="eyebrow">TẤT CẢ GHI CHÚ</span><h2>{filtered.length} ghi chú</h2></div><div className="denseSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm ghi chú…"/></div></div><div className="notesDenseGrid">{filtered.map(n=><article key={n.id} className={n.is_done?'done':''}><div className="noteCheck"><input type="checkbox" checked={!!n.is_done} onChange={e=>patch(n.id,{is_done:e.target.checked})}/></div><div className="noteMain"><b>{n.title||'Ghi chú'}</b>{n.content&&<p>{n.content}</p>}<div className="noteMeta"><span>◷ {dt(n.created_at)}</span>{n.remind_at&&<strong>📅 {dt(n.remind_at)}</strong>}</div></div><button className="noteDelete" onClick={()=>del(n.id)}>×</button></article>)}{!filtered.length&&<div className="empty">Chưa có ghi chú.</div>}</div></section></>
}
