'use client'
import { useEffect,useState } from 'react'
import { useAuth } from '@/components/AuthGate'

export default function Admin(){
 const{user}=useAuth();const[items,setItems]=useState<any[]>([]),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[phone,setPhone]=useState(''),[msg,setMsg]=useState('');
 const[resetUser,setResetUser]=useState<any|null>(null),[resetPassword,setResetPassword]=useState('')
 async function load(){const d=await fetch('/api/admin/users').then(r=>r.json());setItems(d.items||[]);if(d.error)setMsg(d.error)}
 useEffect(()=>{if(user?.role==='admin')load()},[user])
 async function create(){const r=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password,phone})});const d=await r.json();if(!r.ok){setMsg(d.error||'Lỗi');return}setUsername('');setPassword('');setPhone('');setMsg('Đã tạo tài khoản ✓');load()}
 async function patch(id:string,p:any){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...p})});const d=await r.json();if(!r.ok){setMsg(d.error||'Lỗi');return false}await load();return true}
 function edit(x:any){const username=prompt('Tên đăng nhập',x.username);if(username===null)return;const phone=prompt('SĐT (có thể để trống)',x.phone||'');if(phone===null)return;patch(x.id,{username,phone})}
 async function confirmReset(){if(!resetUser||resetPassword==='')return;const ok=await patch(resetUser.id,{new_password:resetPassword});if(ok){setMsg(`Đã cấp lại mật khẩu cho ${resetUser.username} ✓`);setResetPassword('');setResetUser(null)}}
 if(user?.role!=='admin')return <div className="notice">Bạn không có quyền quản trị.</div>
 return <><header className="top"><div><span className="eyebrow">ADMIN</span><h1>Quản trị tài khoản</h1><p>Tạo, sửa, khóa/mở khóa và cấp lại mật khẩu cho người dùng.</p></div></header>
 <section className="adminCreate"><div><h2>Cấp tài khoản mới</h2><p>Mỗi tài khoản có kho dữ liệu riêng và dùng đầy đủ tính năng Second Brain.</p></div><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Tên đăng nhập" autoComplete="off"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" autoComplete="new-password"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="SĐT (không bắt buộc)"/><button className="primary" onClick={create}>＋ Tạo tài khoản</button></section>
 {msg&&<div className="adminMsg">{msg}</div>}
 <section className="userTableCard"><div className="denseTop"><div><span className="eyebrow">NGƯỜI DÙNG</span><h2>{items.length} tài khoản</h2></div></div><div className="userTableWrap"><table className="userTable"><thead><tr><th>Tài khoản</th><th>SĐT</th><th>Quyền</th><th>Trạng thái</th><th>Đăng nhập gần nhất</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.username}</b><small>{new Date(x.created_at).toLocaleString('vi-VN')}</small></td><td>{x.phone||'—'}</td><td><span className={`roleChip ${x.role}`}>{x.role==='admin'?'Admin':'User'}</span></td><td><span className={x.is_locked?'locked':'activeState'}>{x.is_locked?'● Đã khóa':'● Hoạt động'}</span></td><td>{x.last_login_at?new Date(x.last_login_at).toLocaleString('vi-VN'):'—'}</td><td><div className="adminActions"><button onClick={()=>edit(x)}>Sửa</button><button onClick={()=>{setResetUser(x);setResetPassword('')}}>Cấp MK</button><button className={x.is_locked?'unlock':'lock'} onClick={()=>patch(x.id,{is_locked:!x.is_locked})}>{x.is_locked?'Mở khóa':'Khóa'}</button></div></td></tr>)}</tbody></table></div></section>
 {resetUser&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setResetUser(null)}}><section className="passwordModal"><button className="modalClose" onClick={()=>setResetUser(null)}>×</button><span className="eyebrow">CẤP LẠI MẬT KHẨU</span><h2>{resetUser.username}</h2><p>Nhập mật khẩu mới. Mật khẩu không được hiển thị trên giao diện.</p><label>Mật khẩu mới<input autoFocus type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} autoComplete="new-password" onKeyDown={e=>{if(e.key==='Enter')confirmReset()}}/></label><div className="modalActions"><button onClick={()=>setResetUser(null)}>Hủy</button><button className="primary" disabled={resetPassword===''} onClick={confirmReset}>Cập nhật</button></div></section></div>}
 </>
}
