'use client'
import { useEffect, useState } from 'react'
import { loadAISettings } from '@/lib/client-ai-settings'
export default function AddKnowledge({ onSaved }: { onSaved?: () => void }) {
  const [open,setOpen]=useState(false),[title,setTitle]=useState(''),[content,setContent]=useState(''),[category,setCategory]=useState('Learning'),[topic,setTopic]=useState(''),[tags,setTags]=useState(''),[sourceUrl,setSourceUrl]=useState(''),[msg,setMsg]=useState('')
  useEffect(()=>{const fn=()=>setOpen(true);window.addEventListener('second-brain-open-capture',fn);return()=>window.removeEventListener('second-brain-open-capture',fn)},[])
  async function save(){if(!title.trim()||!content.trim())return setMsg('Hãy nhập tiêu đề và nội dung.');setMsg('Đang lưu…');const r=await fetch('/api/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,content,category,topic,tags:tags.split(',').map(x=>x.trim()).filter(Boolean),sourceUrl,aiSettings:loadAISettings()})});const d=await r.json();if(!r.ok)return setMsg(d.error||'Không thể lưu');setTitle('');setContent('');setTopic('');setTags('');setSourceUrl('');setMsg('Đã lưu vào Second Brain ✓');onSaved?.();setTimeout(()=>setOpen(false),650)}
  return <><button className="primary" onClick={()=>setOpen(true)}>＋ Lưu kiến thức</button>{open&&<div className="modalBg" onMouseDown={()=>setOpen(false)}><div className="modal captureModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">QUICK CAPTURE</span><h2>Lưu vào Second Brain</h2><p>Ghi lại nhanh, phân loại sau vẫn được.</p></div><button className="iconBtn" onClick={()=>setOpen(false)}>×</button></div><div className="twoCols"><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Learning, Project, Code..."/></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="React, Vercel, PES..."/></label></div><label>Tiêu đề<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Bạn vừa học được điều gì?"/></label><label>Nội dung<textarea rows={8} value={content} onChange={e=>setContent(e.target.value)} placeholder="Dán kiến thức, ghi chú, code, kết luận..."/></label><div className="twoCols"><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="vercel, deploy, nextjs"/></label><label>URL nguồn<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://..."/></label></div><div className="modalFoot"><span>{msg}</span><button className="primary" onClick={save}>Lưu dài hạn</button></div></div></div>}</>
}
