'use client'
import { useEffect,useMemo,useState } from 'react'
import { loadAISettings,makeAccount,providerCatalog,saveAISettings,type ClientAISettings,type ProviderType } from '@/lib/client-ai-settings'
const providers:ProviderType[]=['gemini','openai','groq','xai','anthropic','openrouter','deepseek','mistral','custom']
const icon=(p:ProviderType)=>p==='gemini'?'✦':p==='openai'?'◌':p==='groq'?'G':p==='xai'?'𝕏':p==='anthropic'?'A':p==='openrouter'?'↗':p==='deepseek'?'D':p==='mistral'?'M':'</>'
export default function AIModelsClient(){
 const[s,setS]=useState<ClientAISettings|null>(null),[provider,setProvider]=useState<ProviderType>('gemini'),[key,setKey]=useState(''),[model,setModel]=useState(providerCatalog.gemini.model),[name,setName]=useState('Gemini chính'),[priority,setPriority]=useState(10),[msg,setMsg]=useState(''),[testing,setTesting]=useState('')
 useEffect(()=>setS(loadAISettings()),[]);useEffect(()=>{setModel(providerCatalog[provider].model);setName(`${providerCatalog[provider].name} chính`)},[provider])
 const accounts=s?.accounts||[];const configured=accounts.filter(a=>a.enabled&&a.apiKey.trim());const providerCount=new Set(configured.map(a=>a.provider)).size
 const ordered=useMemo(()=>[...accounts].sort((a,b)=>(a.priority??100)-(b.priority??100)),[accounts])
 function commit(next:ClientAISettings){setS(next);saveAISettings(next)}
 function add(){if(!s||!key.trim())return setMsg('Dán API key trước.');const a=makeAccount(provider,accounts.filter(x=>x.provider===provider).length+1);Object.assign(a,{name:name.trim()||a.name,apiKey:key.trim(),model:model.trim()||providerCatalog[provider].model,priority,enabled:true});commit({...s,accounts:[...accounts.filter(x=>x.apiKey.trim()),a]});setKey('');setMsg('Đã lưu tài khoản AI ✓')}
 function patch(id:string,p:any){if(!s)return;commit({...s,accounts:accounts.map(a=>a.id===id?{...a,...p}:a)})}
 function remove(id:string){if(!s||!confirm('Xóa API key này khỏi trình duyệt?'))return;commit({...s,activeAccount:s.activeAccount===id?'auto':s.activeAccount,accounts:accounts.filter(a=>a.id!==id)})}
 async function test(id:string){if(!s)return;const a=accounts.find(x=>x.id===id);if(!a?.apiKey.trim())return;setTesting(id);setMsg('Đang kiểm tra kết nối…');try{const one={...s,activeAccount:id,autoRotate:false,accounts:[a]};const r=await fetch('/api/ai/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({aiSettings:one})});const d=await r.json();setMsg(r.ok?`✓ ${a.name} hoạt động · ${d.model}`:`✕ ${d.error||'Kết nối thất bại'}`)}catch{setMsg('✕ Không kết nối được server')}setTesting('')}
 if(!s)return <div className="loadingCard">Đang tải AI Vault…</div>
 return <><header className="pageHeader"><div><span className="eyebrow">MULTI-AI VAULT</span><h1>AI Models</h1><p>Kết nối và quản lý nhiều model, nhiều tài khoản và nhiều API key mà không cần sửa ENV trên Vercel.</p></div><div className="headerBadge"><b>{configured.length}</b><span>API đang hoạt động</span></div></header>
 <section className="aiOverview"><div><span>NHÀ CUNG CẤP</span><b>{providerCount}</b></div><div><span>TÀI KHOẢN</span><b>{configured.length}</b></div><div><span>SMART ROUTING</span><b>{s.autoRotate?'BẬT':'TẮT'}</b></div><label className="routeSwitch"><input type="checkbox" checked={s.autoRotate} onChange={e=>commit({...s,autoRotate:e.target.checked})}/><span/><em>Tự chuyển khi lỗi/hết quota</em></label></section>
 <section className="setupWizard"><div className="sectionHeading"><div><span className="eyebrow">THIẾT LẬP NHANH</span><h2>Kết nối AI trong 4 bước</h2></div><span className="softPill">API key chỉ lưu trên thiết bị</span></div><div className="wizardGrid"><article><div className="stepNo">1</div><h3>Chọn Provider</h3><div className="providerStack">{providers.map(p=><button key={p} className={provider===p?'active':''} onClick={()=>setProvider(p)}><i>{icon(p)}</i><span>{providerCatalog[p].name}</span></button>)}</div></article><article><div className="stepNo">2</div><h3>Dán API Key</h3><label>Tên tài khoản<input value={name} onChange={e=>setName(e.target.value)}/></label><label>API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder={providerCatalog[provider].placeholder}/></label>{provider==='custom'&&<label>Base URL<input placeholder="https://host/v1"/></label>}<small>Không đưa key lên GitHub hoặc Supabase.</small></article><article><div className="stepNo">3</div><h3>Chọn Model</h3><label>Model<input value={model} onChange={e=>setModel(e.target.value)}/></label><label>Ưu tiên<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={10}>Cao · dùng trước</option><option value={50}>Trung bình</option><option value={100}>Dự phòng</option></select></label><div className="modelHint">Gợi ý hiện tại<br/><b>{providerCatalog[provider].model}</b></div></article><article><div className="stepNo">4</div><h3>Lưu & sử dụng</h3><div className="readyBox"><i>✓</i><b>{providerCatalog[provider].name}</b><span>{model}</span><small>Priority {priority}</small></div><button className="primary full" onClick={add}>Lưu API</button><p className="inlineStatus">{msg}</p></article></div></section>
 <section className="accountsSection"><div className="sectionHeading"><div><span className="eyebrow">MULTI ACCOUNT</span><h2>Nhiều tài khoản / Nhiều key</h2></div><select className="activeSelect" value={s.activeAccount} onChange={e=>commit({...s,activeAccount:e.target.value})}><option value="auto">Tự động theo Priority</option>{ordered.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>{ordered.length===0?<div className="empty">Chưa có API key nào. Hãy thêm tài khoản đầu tiên ở phía trên.</div>:<div className="accountTiles">{ordered.map(a=><article className={!a.enabled?'disabled':''} key={a.id}><div className="accountTitle"><i>{icon(a.provider)}</i><div><b>{a.name}</b><span>{providerCatalog[a.provider].name}</span></div><label className="miniSwitch"><input type="checkbox" checked={a.enabled} onChange={e=>patch(a.id,{enabled:e.target.checked})}/><span/></label></div><div className="accountMeta"><span>Model <b>{a.model}</b></span><span>Key <b>••••••{a.apiKey.slice(-4)||'—'}</b></span><span>Priority <b>{a.priority}</b></span></div><div className="accountActions"><button onClick={()=>test(a.id)} disabled={testing===a.id}>{testing===a.id?'Đang test…':'Kiểm tra'}</button><button onClick={()=>patch(a.id,{priority:Math.max(1,(a.priority||100)-10)})}>Ưu tiên ↑</button><button className="dangerText" onClick={()=>remove(a.id)}>Xóa</button></div></article>)}</div>}</section>
 <section className="securityBanner"><div>♢</div><div><b>An toàn & dữ liệu riêng</b><p>Second Brain lưu API key trong Local Storage của trình duyệt hiện tại. Key không được ghi vào Supabase hoặc source GitHub.</p></div></section></>
}
