'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { loadAISettings,makeAccount,providerCatalog,saveAISettings,type ClientAISettings,type ProviderType } from '@/lib/client-ai-settings'
const quickProviders:ProviderType[]=['gemini','openai','groq','xai','anthropic','openrouter','deepseek','mistral','custom']
export default function AISettings(){
 const[open,setOpen]=useState(false),[provider,setProvider]=useState<ProviderType>('gemini'),[name,setName]=useState('Gemini cá nhân'),[key,setKey]=useState(''),[model,setModel]=useState(providerCatalog.gemini.model),[priority,setPriority]=useState(10),[testing,setTesting]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{const p=providerCatalog[provider];setModel(p.model);setName(`${p.name} cá nhân`)},[provider])
 async function save(test=false){if(!key.trim())return setMsg('Hãy dán API key.');const s=loadAISettings();const a=makeAccount(provider,s.accounts.filter(x=>x.provider===provider).length+1);Object.assign(a,{name:name.trim()||a.name,apiKey:key.trim(),model:model.trim()||providerCatalog[provider].model,priority,enabled:true});const next:ClientAISettings={...s,accounts:[...s.accounts.filter(x=>x.apiKey.trim()),a]};saveAISettings(next);if(!test){setMsg('Đã lưu ✓');setTimeout(()=>setOpen(false),500);return}setTesting(true);setMsg('Đang kiểm tra…');try{const one={...next,activeAccount:a.id,autoRotate:false,accounts:[a]};const r=await fetch('/api/ai/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({aiSettings:one})});const d=await r.json();setMsg(r.ok?`Kết nối thành công · ${d.model}`:d.error||'Kết nối thất bại')}catch{setMsg('Không kết nối được server.')}setTesting(false)}
 return <><button className="aiSettingsBtn" onClick={()=>setOpen(true)}>＋ Thêm API</button>{open&&<div className="modalBg" onMouseDown={()=>setOpen(false)}><div className="modal quickApiModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">AI CONNECTION</span><h2>Thêm API</h2><p>Chỉ 4 bước: chọn hãng → dán key → chọn model → lưu.</p></div><button className="iconBtn" onClick={()=>setOpen(false)}>×</button></div><div className="providerPicker">{quickProviders.map(p=><button key={p} className={provider===p?'active':''} onClick={()=>setProvider(p)}><span>{p==='gemini'?'✦':p==='openai'?'◌':p==='groq'?'G':p==='xai'?'𝕏':p==='anthropic'?'A':p==='openrouter'?'↗':p==='deepseek'?'D':p==='mistral'?'M':'</>'}</span>{providerCatalog[p].name.replace(' / ChatGPT','')}</button>)}</div><div className="apiFormSimple"><label>Tên tài khoản<input value={name} onChange={e=>setName(e.target.value)} placeholder="VD: Gemini chính"/></label><label>API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder={providerCatalog[provider].placeholder}/></label><label>Model<input value={model} onChange={e=>setModel(e.target.value)} /></label><label>Ưu tiên<select value={priority} onChange={e=>setPriority(Number(e.target.value))}><option value={10}>Ưu tiên cao</option><option value={50}>Trung bình</option><option value={100}>Dự phòng</option></select></label></div><div className="quickApiHelp">Key chỉ lưu trên trình duyệt này. Bạn có thể quản lý nhiều tài khoản/key trong trang <b>AI Models</b>.</div><div className="modalFoot"><span>{msg}</span><div className="buttonRow"><Link className="secondary linkBtn" href="/ai-models" onClick={()=>setOpen(false)}>Quản lý nâng cao</Link><button className="secondary" onClick={()=>save(true)} disabled={testing}>{testing?'Đang test…':'Kiểm tra'}</button><button className="primary" onClick={()=>save(false)}>Lưu API</button></div></div></div></div>}</>
}
