'use client'
import { useMemo,useState } from 'react'
function norm(s:string){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase()}
function dt(v:string){if(!v)return '—';try{return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}}
export default function KnowledgeTree({items,onChanged}:{items:any[],onChanged:()=>void}){
 const[q,setQ]=useState('');const[editing,setEditing]=useState<any|null>(null)
 const filtered=useMemo(()=>{const x=norm(q).trim();const arr=x?items.filter(n=>norm([n.category,n.topic,n.metadata?.topic,n.title,n.content,(n.tags||n.metadata?.tags||[]).join(' ')].join(' ')).includes(x)):items;return [...arr].sort((a,b)=>new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime())},[q,items])
 async function del(id:string){if(!confirm('Xóa kiến thức này?'))return;await fetch('/api/knowledge/item',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});onChanged()}
 async function save(){if(!editing)return;const tags=Array.isArray(editing.tags)?editing.tags:String(editing.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean);await fetch('/api/knowledge/item',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...editing,tags})});setEditing(null);onChanged()}
 return <section className="knowledgeVaultDense">
  <div className="denseTop"><div><span className="eyebrow">TẤT CẢ KIẾN THỨC</span><h2>{filtered.length} kiến thức</h2><p>Luôn hiển thị để quan sát nhanh — mới nhất ở trên.</p></div><div className="denseSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tiêu đề, nội dung, topic, category, tag…"/></div></div>
  <div className="knowledgeTableWrap"><table className="knowledgeTable"><thead><tr><th>Tiêu đề</th><th>Nội dung</th><th>Topic</th><th>Category</th><th>Tag</th><th>Ngày giờ</th><th></th></tr></thead><tbody>{filtered.map((n:any)=>{const tg=n.tags||n.metadata?.tags||[];return <tr key={n.id}><td className="kTitle" title={n.title||''}>{n.title||<em>Không tiêu đề</em>}</td><td className="kContent" title={n.content||''}>{n.content||<span className="mutedDash">—</span>}</td><td><span className="metaChip">{n.topic||n.metadata?.topic||'—'}</span></td><td><span className="metaChip categoryChip">{n.category||'General'}</span></td><td><div className="denseTags">{tg.length?tg.slice(0,3).map((x:string)=><i key={x}>#{x}</i>):<span>—</span>}{tg.length>3&&<b>+{tg.length-3}</b>}</div></td><td className="kDate">{dt(n.created_at)}</td><td><div className="rowActions"><button title="Sửa" onClick={()=>setEditing({...n,tags:tg.join(', ')})}>✎</button><button title="Xóa" className="dangerText" onClick={()=>del(n.id)}>×</button></div></td></tr>})}{!filtered.length&&<tr><td colSpan={7} className="emptyRow">Chưa có kiến thức phù hợp.</td></tr>}</tbody></table></div>
  {editing&&<div className="modalBg" onMouseDown={()=>setEditing(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">CHỈNH SỬA</span><h2>Sửa kiến thức</h2><p>Tạo lúc {dt(editing.created_at)}</p></div><button className="iconBtn" onClick={()=>setEditing(null)}>×</button></div><label>Nội dung<textarea rows={7} value={editing.content||''} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><label>Tiêu đề<input value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><div className="twoCols"><label>Topic<input value={editing.topic||editing.metadata?.topic||''} onChange={e=>setEditing({...editing,topic:e.target.value})}/></label><label>Category<input value={editing.category||''} onChange={e=>setEditing({...editing,category:e.target.value})}/></label></div><label>Tag<input value={editing.tags||''} onChange={e=>setEditing({...editing,tags:e.target.value})}/></label><div className="modalFoot"><span></span><button className="primary" onClick={save}>Cập nhật</button></div></div></div>}
 </section>
}
