'use client'
import { useMemo,useState } from 'react'
function norm(s:string){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase()}
export default function KnowledgeTree({items,onChanged}:{items:any[],onChanged:()=>void}){
 const[q,setQ]=useState('');const[open,setOpen]=useState<Record<string,boolean>>({}); const [editing,setEditing]=useState<any|null>(null)
 const filtered=useMemo(()=>{const x=norm(q).trim();return x?items.filter(n=>norm([n.category,n.topic,n.metadata?.topic,n.title,n.content,(n.tags||n.metadata?.tags||[]).join(' ')].join(' ')).includes(x)):items},[q,items])
 const groups=useMemo(()=>{const g:any={};for(const n of filtered){const c=n.category||'General',t=n.topic||n.metadata?.topic||'Không phân Topic';(((g[c]??={})[t]??=[])).push(n)}return g},[filtered])
 async function del(id:string){if(!confirm('Xóa kiến thức này?'))return;await fetch('/api/knowledge/item',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});onChanged()}
 async function save(){if(!editing)return;await fetch('/api/knowledge/item',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...editing,tags:Array.isArray(editing.tags)?editing.tags:String(editing.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean)})});setEditing(null);onChanged()}
 return <section className="treeCard"><div className="treeTop"><div><span className="eyebrow">CATEGORY → TOPIC → KNOWLEDGE</span><h2>Kho kiến thức có cấu trúc</h2></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm không dấu cũng được..."/></div>
 <div className="treeBody">{Object.keys(groups).sort().map(c=><div className="treeCategory" key={c}><button onClick={()=>setOpen(o=>({...o,['c:'+c]:!o['c:'+c]}))}><b>{c}</b><span>{open['c:'+c]?'−':'+'}</span></button>{open['c:'+c]&&<div>{Object.keys(groups[c]).sort().map(t=><div className="treeTopic" key={t}><button onClick={()=>setOpen(o=>({...o,['t:'+c+t]:!o['t:'+c+t]}))}><b>{t}</b><span>{groups[c][t].length} · {open['t:'+c+t]?'−':'+'}</span></button>{open['t:'+c+t]&&<div className="treeNotes">{groups[c][t].map((n:any)=><article key={n.id}><div><h4>{n.title}</h4><p>{n.content}</p><div className="tagRow">{(n.tags||n.metadata?.tags||[]).map((x:string)=><i key={x}>#{x}</i>)}</div></div><div className="noteActions"><button onClick={()=>setEditing({...n,tags:(n.tags||n.metadata?.tags||[]).join(', ')})}>Sửa</button><button className="dangerText" onClick={()=>del(n.id)}>Xóa</button></div></article>)}</div>}</div>)}</div>}</div>)}</div>
 {editing&&<div className="modalBg" onMouseDown={()=>setEditing(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><h2>Sửa kiến thức</h2><button className="iconBtn" onClick={()=>setEditing(null)}>×</button></div><div className="twoCols"><label>Category<input value={editing.category||''} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label>Topic<input value={editing.topic||editing.metadata?.topic||''} onChange={e=>setEditing({...editing,topic:e.target.value})}/></label></div><label>Tiêu đề<input value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Nội dung<textarea rows={9} value={editing.content||''} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><label>Tags<input value={editing.tags||''} onChange={e=>setEditing({...editing,tags:e.target.value})}/></label><div className="modalFoot"><span></span><button className="primary" onClick={save}>Cập nhật</button></div></div></div>}
 </section>
}
